---
language: ruby
bundler_args: --without system_tests --jobs 3 --retry 3
before_install: rm Gemfile.lock || true
sudo: false
script: "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec"
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.6
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES=yes ORDERING=random
notifications:
  email:
    - project@bendler-net.de
